### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by taoholl** [beta-mtn/web-app#8]
PROGRESS REPORT JAN 29 2018

**Discuss team dynamics & member contributions**

Discuss successes & failures
greatest success of the day was figuring out the direction of our app and starting the app flow for interactive wireframe. Failures were not figuring out the direction before class. To correct this our team will be meeting through out the week to ensure time is well spent.

Ask questions & get help
Met with professor to pitch app idea. Was given guidance which pointed us in the right direction and allowed us to focus our time.

Created Schedule and tasks for next week

@thomasjbradley

**Comment by taoholl** [comment]
Tasks:
Researching unique ideas on Calendar apps.
Came up with tasks for Calendar app
Worked as a team to solidify concept and app focus
Created wire frame mock for pitch to team
Delegated time management and booked a meeting for Wednesday

Reflection:
Missing the class last week really affected this weeks productivity. Feeling that our team is still not on track and that communication needs to be addressed. A team meeting as been scheduled for Wednesday to ensure all team members are on track and are on the same page. Delegating work has also been an issue.

**Comment by majabbergstrom** [comment]
Research on competitors, successful Calendar apps
Worked as a team to solidify concept and app focus
Helped team lead get up to speed on class missed
Created Rubrics

Reflection:
The week was a bit rocky because team lead missed the class so first round of delegation was left to me. The tasks that were delegated for the week were relatively simple things because we didn't have a chance to meet for a long amount of time to discuss the project, which affected this week's productivity.

**Comment by Nasrine** [comment]
Research on the negative aspects of Calendar apps "Student's Task Manager" and "Fantastical" to gain insight for our app.
Worked as a team to solidify concept and app focus

**Comment by thomasjbradley** [comment]
I’d like to see the reflections be a little more personal, use "I" instead of "We".

---

The Issues in Sprint 2 are well detailed, but they do not seem to be up to day. There are still some Issues open and many of the checkboxes aren't checked off but the Issue is still closed.
